before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install bash; fi' # Bash4 Required
language: generic
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.2
    - os: osx
      osx_image: xcode10.3
    #- os: osx
    #  osx_image: xcode9.4  # brew update is excruciatingly slow on xcode9.4
script:
  - ./test/run.sh
